/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-02-25 09:20:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inscription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-3\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"ressource/css/inscription.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Inscription</h1>\r\n");
      out.write("<form action=\"inscription\" method=\"post\" class=\"color\">\r\n");
      out.write("    <fieldset>\r\n");
      out.write("        <legend>Vos Coordonnées</legend>\r\n");
      out.write("        <label>Mme</label>\r\n");
      out.write("        <input type=\"radio\" name=\"Civilite\" value=\"1\" checked>\r\n");
      out.write("        <label>Mr</label>\r\n");
      out.write("        <input type=\"radio\" name=\"Civilite\" value=\"2\" >\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <label>Nom :</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"text\" name=\"nom\" placeholder=\"Nom\" id=\"nom\" class=\"dim_block2\" id=\"colorBlock\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Prénom :</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"text\" name=\"prenom\" placeholder=\"Prénom\" id=\"prenom\" class=\"dim_block2\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Date de Naissance :</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"date\" name=\"date_naissance\" id=\"date_naissance\" class=\"dim_block2\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>N° et rue :</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"text\" name=\"numero_rue\" placeholder=\"N° et rue\" id=\"N° et rue\" class=\"dim_block2\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Ville</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"text\" name=\"ville\" placeholder=\"Votre ville\" id=\"voter ville\" class=\"dim_block2\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Département</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <select name=\"departement\" id=\"departement\" class=\"dim_block2\">\r\n");
      out.write("            <option value=\"00\">(00) Hors France</option>\r\n");
      out.write("            <option value=\"01\">(01) Ain </option>\r\n");
      out.write("            <option value=\"02\">(02) Aisne </option>\r\n");
      out.write("            <option value=\"03\">(03) Allier </option>\r\n");
      out.write("            <option value=\"04\">(04) Alpes de Haute Provence </option>\r\n");
      out.write("            <option value=\"05\">(05) Hautes Alpes </option>\r\n");
      out.write("            <option value=\"06\">(06) Alpes Maritimes </option>\r\n");
      out.write("            <option value=\"07\">(07) Ardèche </option>\r\n");
      out.write("            <option value=\"08\">(08) Ardennes </option>\r\n");
      out.write("            <option value=\"09\">(09) Ariège </option>\r\n");
      out.write("            <option value=\"10\">(10) Aube </option>\r\n");
      out.write("            <option value=\"11\">(11) Aude </option>\r\n");
      out.write("            <option value=\"12\">(12) Aveyron </option>\r\n");
      out.write("            <option value=\"13\">(13) Bouches du Rhône </option>\r\n");
      out.write("            <option value=\"14\">(14) Calvados </option>\r\n");
      out.write("            <option value=\"15\">(15) Cantal </option>\r\n");
      out.write("            <option value=\"16\">(16) Charente </option>\r\n");
      out.write("            <option value=\"17\">(17) Charente Maritime </option>\r\n");
      out.write("            <option value=\"18\">(18) Cher </option>\r\n");
      out.write("            <option value=\"19\">(19) Corrèze </option>\r\n");
      out.write("            <option value=\"2A\">(2A) Corse du Sud </option>\r\n");
      out.write("            <option value=\"2B\">(2B) Haute-Corse </option>\r\n");
      out.write("            <option value=\"21\">(21) Côte d'Or </option>\r\n");
      out.write("            <option value=\"22\">(22) Côtes d'Armor </option>\r\n");
      out.write("            <option value=\"23\">(23) Creuse </option>\r\n");
      out.write("            <option value=\"24\">(24) Dordogne </option>\r\n");
      out.write("            <option value=\"25\">(25) Doubs </option>\r\n");
      out.write("            <option value=\"26\">(26) Drôme </option>\r\n");
      out.write("            <option value=\"27\">(27) Eure </option>\r\n");
      out.write("            <option value=\"28\">(28) Eure et Loir </option>\r\n");
      out.write("            <option value=\"29\">(29) Finistère </option>\r\n");
      out.write("            <option value=\"30\">(30) Gard </option>\r\n");
      out.write("            <option value=\"31\">(31) Haute Garonne </option>\r\n");
      out.write("            <option value=\"32\">(32) Gers </option>\r\n");
      out.write("            <option value=\"33\">(33) Gironde </option>\r\n");
      out.write("            <option value=\"34\">(34) Hérault </option>\r\n");
      out.write("            <option value=\"35\">(35) Ille et Vilaine </option>\r\n");
      out.write("            <option value=\"36\">(36) Indre </option>\r\n");
      out.write("            <option value=\"37\">(37) Indre et Loire </option>\r\n");
      out.write("            <option value=\"38\">(38) Isère </option>\r\n");
      out.write("            <option value=\"39\">(39) Jura </option>\r\n");
      out.write("            <option value=\"40\">(40) Landes </option>\r\n");
      out.write("            <option value=\"41\">(41) Loir et Cher </option>\r\n");
      out.write("            <option value=\"42\">(42) Loire </option>\r\n");
      out.write("            <option value=\"43\">(43) Haute Loire </option>\r\n");
      out.write("            <option value=\"44\">(44) Loire Atlantique </option>\r\n");
      out.write("            <option value=\"45\">(45) Loiret </option>\r\n");
      out.write("            <option value=\"46\">(46) Lot </option>\r\n");
      out.write("            <option value=\"47\">(47) Lot et Garonne </option>\r\n");
      out.write("            <option value=\"48\">(48) Lozère </option>\r\n");
      out.write("            <option value=\"49\">(49) Maine et Loire </option>\r\n");
      out.write("            <option value=\"50\">(50) Manche </option>\r\n");
      out.write("            <option value=\"51\">(51) Marne </option>\r\n");
      out.write("            <option value=\"52\">(52) Haute Marne </option>\r\n");
      out.write("            <option value=\"53\">(53) Mayenne </option>\r\n");
      out.write("            <option value=\"54\">(54) Meurthe et Moselle </option>\r\n");
      out.write("            <option value=\"55\">(55) Meuse </option>\r\n");
      out.write("            <option value=\"56\">(56) Morbihan </option>\r\n");
      out.write("            <option value=\"57\">(57) Moselle </option>\r\n");
      out.write("            <option value=\"58\">(58) Nièvre </option>\r\n");
      out.write("            <option value=\"59\">(59) Nord </option>\r\n");
      out.write("            <option value=\"60\">(60) Oise </option>\r\n");
      out.write("            <option value=\"61\">(61) Orne </option>\r\n");
      out.write("            <option value=\"62\">(62) Pas de Calais </option>\r\n");
      out.write("            <option value=\"63\">(63) Puy de Dôme </option>\r\n");
      out.write("            <option value=\"64\">(64) Pyrénées Atlantiques </option>\r\n");
      out.write("            <option value=\"65\">(65) Hautes Pyrénées </option>\r\n");
      out.write("            <option value=\"66\">(66) Pyrénées Orientales </option>\r\n");
      out.write("            <option value=\"67\">(67) Bas Rhin </option>\r\n");
      out.write("            <option value=\"68\">(68) Haut Rhin </option>\r\n");
      out.write("            <option value=\"69\">(69) Rhône </option>\r\n");
      out.write("            <option value=\"70\">(70) Haute Saône </option>\r\n");
      out.write("            <option value=\"71\">(71) Saône et Loire </option>\r\n");
      out.write("            <option value=\"72\">(72) Sarthe </option>\r\n");
      out.write("            <option value=\"73\">(73) Savoie </option>\r\n");
      out.write("            <option value=\"74\">(74) Haute Savoie </option>\r\n");
      out.write("            <option value=\"75\">(75) Paris </option>\r\n");
      out.write("            <option value=\"76\">(76) Seine Maritime </option>\r\n");
      out.write("            <option value=\"77\">(77) Seine et Marne </option>\r\n");
      out.write("            <option value=\"78\">(78) Yvelines </option>\r\n");
      out.write("            <option value=\"79\">(79) Deux Sèvres </option>\r\n");
      out.write("            <option value=\"80\">(80) Somme </option>\r\n");
      out.write("            <option value=\"81\">(81) Tarn </option>\r\n");
      out.write("            <option value=\"82\">(82) Tarn et Garonne </option>\r\n");
      out.write("            <option value=\"83\">(83) Var </option>\r\n");
      out.write("            <option value=\"84\">(84) Vaucluse </option>\r\n");
      out.write("            <option value=\"85\">(85) Vendée </option>\r\n");
      out.write("            <option value=\"86\">(86) Vienne </option>\r\n");
      out.write("            <option value=\"87\">(87) Haute Vienne </option>\r\n");
      out.write("            <option value=\"88\">(88) Vosges </option>\r\n");
      out.write("            <option value=\"89\">(89) Yonne </option>\r\n");
      out.write("            <option value=\"90\">(90) Territoire de Belfort </option>\r\n");
      out.write("            <option value=\"91\">(91) Essonne </option>\r\n");
      out.write("            <option value=\"92\">(92) Hauts de Seine </option>\r\n");
      out.write("            <option value=\"93\">(93) Seine Saint Denis </option>\r\n");
      out.write("            <option value=\"94\">(94) Val de Marne </option>\r\n");
      out.write("            <option value=\"95\">(95) Val d'Oise </option>\r\n");
      out.write("            <option value=\"971\">(971) Guadeloupe </option>\r\n");
      out.write("            <option value=\"972\">(972) Martinique </option>\r\n");
      out.write("            <option value=\"973\">(973) Guyane </option>\r\n");
      out.write("            <option value=\"974\">(974) Réunion </option>\r\n");
      out.write("            <option value=\"975\">(975) Saint Pierre et Miquelon </option>\r\n");
      out.write("            <option value=\"976\">(976) Mayotte </option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Pays</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <select name=\"pays\" id=\"pays\"class=\"dim_block2\">\r\n");
      out.write("            <option value=\"France\" selected=\"selected\">France</option>\r\n");
      out.write("            <option value=\"Afghanistan\">Afghanistan</option>\r\n");
      out.write("            <option value=\"Afrique_Centrale\">Afrique_Centrale</option>\r\n");
      out.write("            <option value=\"Afrique_du_sud\">Afrique_du_Sud</option>\r\n");
      out.write("            <option value=\"Albanie\">Albanie</option>\r\n");
      out.write("            <option value=\"Algerie\">Algerie</option>\r\n");
      out.write("            <option value=\"Allemagne\">Allemagne</option>\r\n");
      out.write("            <option value=\"Andorre\">Andorre</option>\r\n");
      out.write("            <option value=\"Angola\">Angola</option>\r\n");
      out.write("            <option value=\"Anguilla\">Anguilla</option>\r\n");
      out.write("            <option value=\"Arabie_Saoudite\">Arabie_Saoudite</option>\r\n");
      out.write("            <option value=\"Argentine\">Argentine</option>\r\n");
      out.write("            <option value=\"Armenie\">Armenie</option>\r\n");
      out.write("            <option value=\"Australie\">Australie</option>\r\n");
      out.write("            <option value=\"Autriche\">Autriche</option>\r\n");
      out.write("            <option value=\"Azerbaidjan\">Azerbaidjan</option>\r\n");
      out.write("            <option value=\"Bahamas\">Bahamas</option>\r\n");
      out.write("            <option value=\"Bangladesh\">Bangladesh</option>\r\n");
      out.write("            <option value=\"Barbade\">Barbade</option>\r\n");
      out.write("            <option value=\"Bahrein\">Bahrein</option>\r\n");
      out.write("            <option value=\"Belgique\">Belgique</option>\r\n");
      out.write("            <option value=\"Belize\">Belize</option>\r\n");
      out.write("            <option value=\"Benin\">Benin</option>\r\n");
      out.write("            <option value=\"Bermudes\">Bermudes</option>\r\n");
      out.write("            <option value=\"Bielorussie\">Bielorussie</option>\r\n");
      out.write("            <option value=\"Bolivie\">Bolivie</option>\r\n");
      out.write("            <option value=\"Botswana\">Botswana</option>\r\n");
      out.write("            <option value=\"Bhoutan\">Bhoutan</option>\r\n");
      out.write("            <option value=\"Boznie_Herzegovine\">Boznie_Herzegovine</option>\r\n");
      out.write("            <option value=\"Bresil\">Bresil</option>\r\n");
      out.write("            <option value=\"Brunei\">Brunei</option>\r\n");
      out.write("            <option value=\"Bulgarie\">Bulgarie</option>\r\n");
      out.write("            <option value=\"Burkina_Faso\">Burkina_Faso</option>\r\n");
      out.write("            <option value=\"Burundi\">Burundi</option>\r\n");
      out.write("            <option value=\"Caiman\">Caiman</option>\r\n");
      out.write("            <option value=\"Cambodge\">Cambodge</option>\r\n");
      out.write("            <option value=\"Cameroun\">Cameroun</option>\r\n");
      out.write("            <option value=\"Canada\">Canada</option>\r\n");
      out.write("            <option value=\"Canaries\">Canaries</option>\r\n");
      out.write("            <option value=\"Cap_vert\">Cap_Vert</option>\r\n");
      out.write("            <option value=\"Chili\">Chili</option>\r\n");
      out.write("            <option value=\"Chine\">Chine</option>\r\n");
      out.write("            <option value=\"Chypre\">Chypre</option>\r\n");
      out.write("            <option value=\"Colombie\">Colombie</option>\r\n");
      out.write("            <option value=\"Comores\">Colombie</option>\r\n");
      out.write("            <option value=\"Congo\">Congo</option>\r\n");
      out.write("            <option value=\"Congo_democratique\">Congo_democratique</option>\r\n");
      out.write("            <option value=\"Cook\">Cook</option>\r\n");
      out.write("            <option value=\"Coree_du_Nord\">Coree_du_Nord</option>\r\n");
      out.write("            <option value=\"Coree_du_Sud\">Coree_du_Sud</option>\r\n");
      out.write("            <option value=\"Costa_Rica\">Costa_Rica</option>\r\n");
      out.write("            <option value=\"Cote_d_Ivoire\">Côte_d_Ivoire</option>\r\n");
      out.write("            <option value=\"Croatie\">Croatie</option>\r\n");
      out.write("            <option value=\"Cuba\">Cuba</option>\r\n");
      out.write("            <option value=\"Danemark\">Danemark</option>\r\n");
      out.write("            <option value=\"Djibouti\">Djibouti</option>\r\n");
      out.write("            <option value=\"Dominique\">Dominique</option>\r\n");
      out.write("            <option value=\"Egypte\">Egypte</option>\r\n");
      out.write("            <option value=\"Emirats_Arabes_Unis\">Emirats_Arabes_Unis</option>\r\n");
      out.write("            <option value=\"Equateur\">Equateur</option>\r\n");
      out.write("            <option value=\"Erythree\">Erythree</option>\r\n");
      out.write("            <option value=\"Espagne\">Espagne</option>\r\n");
      out.write("            <option value=\"Estonie\">Estonie</option>\r\n");
      out.write("            <option value=\"Etats_Unis\">Etats_Unis</option>\r\n");
      out.write("            <option value=\"Ethiopie\">Ethiopie</option>\r\n");
      out.write("            <option value=\"Falkland\">Falkland</option>\r\n");
      out.write("            <option value=\"Feroe\">Feroe</option>\r\n");
      out.write("            <option value=\"Fidji\">Fidji</option>\r\n");
      out.write("            <option value=\"Finlande\">Finlande</option>\r\n");
      out.write("            <option value=\"France\">France</option>\r\n");
      out.write("            <option value=\"Gabon\">Gabon</option>\r\n");
      out.write("            <option value=\"Gambie\">Gambie</option>\r\n");
      out.write("            <option value=\"Georgie\">Georgie</option>\r\n");
      out.write("            <option value=\"Ghana\">Ghana</option>\r\n");
      out.write("            <option value=\"Gibraltar\">Gibraltar</option>\r\n");
      out.write("            <option value=\"Grece\">Grece</option>\r\n");
      out.write("            <option value=\"Grenade\">Grenade</option>\r\n");
      out.write("            <option value=\"Groenland\">Groenland</option>\r\n");
      out.write("            <option value=\"Guadeloupe\">Guadeloupe</option>\r\n");
      out.write("            <option value=\"Guam\">Guam</option>\r\n");
      out.write("            <option value=\"Guatemala\">Guatemala</option>\r\n");
      out.write("            <option value=\"Guernesey\">Guernesey</option>\r\n");
      out.write("            <option value=\"Guinee\">Guinee</option>\r\n");
      out.write("            <option value=\"Guinee_Bissau\">Guinee_Bissau</option>\r\n");
      out.write("            <option value=\"Guinee equatoriale\">Guinee_Equatoriale</option>\r\n");
      out.write("            <option value=\"Guyana\">Guyana</option>\r\n");
      out.write("            <option value=\"Guyane_Francaise \">Guyane_Francaise</option>\r\n");
      out.write("            <option value=\"Haiti\">Haiti</option>\r\n");
      out.write("            <option value=\"Hawaii\">Hawaii</option>\r\n");
      out.write("            <option value=\"Honduras\">Honduras</option>\r\n");
      out.write("            <option value=\"Hong_Kong\">Hong_Kong</option>\r\n");
      out.write("            <option value=\"Hongrie\">Hongrie</option>\r\n");
      out.write("            <option value=\"Inde\">Inde</option>\r\n");
      out.write("            <option value=\"Indonesie\">Indonesie</option>\r\n");
      out.write("            <option value=\"Iran\">Iran</option>\r\n");
      out.write("            <option value=\"Iraq\">Iraq</option>\r\n");
      out.write("            <option value=\"Irlande\">Irlande</option>\r\n");
      out.write("            <option value=\"Islande\">Islande</option>\r\n");
      out.write("            <option value=\"Israel\">Israel</option>\r\n");
      out.write("            <option value=\"Italie\">italie</option>\r\n");
      out.write("            <option value=\"Jamaique\">Jamaique</option>\r\n");
      out.write("            <option value=\"Jan Mayen\">Jan Mayen</option>\r\n");
      out.write("            <option value=\"Japon\">Japon</option>\r\n");
      out.write("            <option value=\"Jersey\">Jersey</option>\r\n");
      out.write("            <option value=\"Jordanie\">Jordanie</option>\r\n");
      out.write("            <option value=\"Kazakhstan\">Kazakhstan</option>\r\n");
      out.write("            <option value=\"Kenya\">Kenya</option>\r\n");
      out.write("            <option value=\"Kirghizstan\">Kirghizistan</option>\r\n");
      out.write("            <option value=\"Kiribati\">Kiribati</option>\r\n");
      out.write("            <option value=\"Koweit\">Koweit</option>\r\n");
      out.write("            <option value=\"Laos\">Laos</option>\r\n");
      out.write("            <option value=\"Lesotho\">Lesotho</option>\r\n");
      out.write("            <option value=\"Lettonie\">Lettonie</option>\r\n");
      out.write("            <option value=\"Liban\">Liban</option>\r\n");
      out.write("            <option value=\"Liberia\">Liberia</option>\r\n");
      out.write("            <option value=\"Liechtenstein\">Liechtenstein</option>\r\n");
      out.write("            <option value=\"Lituanie\">Lituanie</option>\r\n");
      out.write("            <option value=\"Luxembourg\">Luxembourg</option>\r\n");
      out.write("            <option value=\"Lybie\">Lybie</option>\r\n");
      out.write("            <option value=\"Macao\">Macao</option>\r\n");
      out.write("            <option value=\"Macedoine\">Macedoine</option>\r\n");
      out.write("            <option value=\"Madagascar\">Madagascar</option>\r\n");
      out.write("            <option value=\"Madère\">Madère</option>\r\n");
      out.write("            <option value=\"Malaisie\">Malaisie</option>\r\n");
      out.write("            <option value=\"Malawi\">Malawi</option>\r\n");
      out.write("            <option value=\"Maldives\">Maldives</option>\r\n");
      out.write("            <option value=\"Mali\">Mali</option>\r\n");
      out.write("            <option value=\"Malte\">Malte</option>\r\n");
      out.write("            <option value=\"Man\">Man</option>\r\n");
      out.write("            <option value=\"Mariannes du Nord\">Mariannes du Nord</option>\r\n");
      out.write("            <option value=\"Maroc\">Maroc</option>\r\n");
      out.write("            <option value=\"Marshall\">Marshall</option>\r\n");
      out.write("            <option value=\"Martinique\">Martinique</option>\r\n");
      out.write("            <option value=\"Maurice\">Maurice</option>\r\n");
      out.write("            <option value=\"Mauritanie\">Mauritanie</option>\r\n");
      out.write("            <option value=\"Mayotte\">Mayotte</option>\r\n");
      out.write("            <option value=\"Mexique\">Mexique</option>\r\n");
      out.write("            <option value=\"Micronesie\">Micronesie</option>\r\n");
      out.write("            <option value=\"Midway\">Midway</option>\r\n");
      out.write("            <option value=\"Moldavie\">Moldavie</option>\r\n");
      out.write("            <option value=\"Monaco\">Monaco</option>\r\n");
      out.write("            <option value=\"Mongolie\">Mongolie</option>\r\n");
      out.write("            <option value=\"Montserrat\">Montserrat</option>\r\n");
      out.write("            <option value=\"Mozambique\">Mozambique</option>\r\n");
      out.write("            <option value=\"Namibie\">Namibie</option>\r\n");
      out.write("            <option value=\"Nauru\">Nauru</option>\r\n");
      out.write("            <option value=\"Nepal\">Nepal</option>\r\n");
      out.write("            <option value=\"Nicaragua\">Nicaragua</option>\r\n");
      out.write("            <option value=\"Niger\">Niger</option>\r\n");
      out.write("            <option value=\"Nigeria\">Nigeria</option>\r\n");
      out.write("            <option value=\"Niue\">Niue</option>\r\n");
      out.write("            <option value=\"Norfolk\">Norfolk</option>\r\n");
      out.write("            <option value=\"Norvege\">Norvege</option>\r\n");
      out.write("            <option value=\"Nouvelle_Caledonie\">Nouvelle_Caledonie</option>\r\n");
      out.write("            <option value=\"Nouvelle_Zelande\">Nouvelle_Zelande</option>\r\n");
      out.write("            <option value=\"Oman\">Oman</option>\r\n");
      out.write("            <option value=\"Ouganda\">Ouganda</option>\r\n");
      out.write("            <option value=\"Ouzbekistan\">Ouzbekistan</option>\r\n");
      out.write("            <option value=\"Pakistan\">Pakistan</option>\r\n");
      out.write("            <option value=\"Palau\">Palau</option>\r\n");
      out.write("            <option value=\"Palestine\">Palestine</option>\r\n");
      out.write("            <option value=\"Panama\">Panama</option>\r\n");
      out.write("            <option value=\"Papouasie_Nouvelle_Guinee\">Papouasie_Nouvelle_Guinee</option>\r\n");
      out.write("            <option value=\"Paraguay\">Paraguay</option>\r\n");
      out.write("            <option value=\"Pays_Bas\">Pays_Bas</option>\r\n");
      out.write("            <option value=\"Perou\">Perou</option>\r\n");
      out.write("            <option value=\"Philippines\">Philippines</option>\r\n");
      out.write("            <option value=\"Pologne\">Pologne</option>\r\n");
      out.write("            <option value=\"Polynesie\">Polynesie</option>\r\n");
      out.write("            <option value=\"Porto_Rico\">Porto_Rico</option>\r\n");
      out.write("            <option value=\"Portugal\">Portugal</option>\r\n");
      out.write("            <option value=\"Qatar\">Qatar</option>\r\n");
      out.write("            <option value=\"Republique_Dominicaine\">Republique_Dominicaine</option>\r\n");
      out.write("            <option value=\"Republique_Tcheque\">Republique_Tcheque</option>\r\n");
      out.write("            <option value=\"Reunion\">Reunion</option>\r\n");
      out.write("            <option value=\"Roumanie\">Roumanie</option>\r\n");
      out.write("            <option value=\"Royaume_Uni\">Royaume_Uni</option>\r\n");
      out.write("            <option value=\"Russie\">Russie</option>\r\n");
      out.write("            <option value=\"Rwanda\">Rwanda</option>\r\n");
      out.write("            <option value=\"Sahara Occidental\">Sahara Occidental</option>\r\n");
      out.write("            <option value=\"Sainte_Lucie\">Sainte_Lucie</option>\r\n");
      out.write("            <option value=\"Saint_Marin\">Saint_Marin</option>\r\n");
      out.write("            <option value=\"Salomon\">Salomon</option>\r\n");
      out.write("            <option value=\"Salvador\">Salvador</option>\r\n");
      out.write("            <option value=\"Samoa_Occidentales\">Samoa_Occidentales</option>\r\n");
      out.write("            <option value=\"Samoa_Americaine\">Samoa_Americaine</option>\r\n");
      out.write("            <option value=\"Sao_Tome_et_Principe\">Sao_Tome_et_Principe</option>\r\n");
      out.write("            <option value=\"Senegal\">Senegal</option>\r\n");
      out.write("            <option value=\"Seychelles\">Seychelles</option>\r\n");
      out.write("            <option value=\"Sierra Leone\">Sierra Leone</option>\r\n");
      out.write("            <option value=\"Singapour\">Singapour</option>\r\n");
      out.write("            <option value=\"Slovaquie\">Slovaquie</option>\r\n");
      out.write("            <option value=\"Slovenie\">Slovenie</option>\r\n");
      out.write("            <option value=\"Somalie\">Somalie</option>\r\n");
      out.write("            <option value=\"Soudan\">Soudan</option>\r\n");
      out.write("            <option value=\"Sri_Lanka\">Sri_Lanka</option>\r\n");
      out.write("            <option value=\"Suede\">Suede</option>\r\n");
      out.write("            <option value=\"Suisse\">Suisse</option>\r\n");
      out.write("            <option value=\"Surinam\">Surinam</option>\r\n");
      out.write("            <option value=\"Swaziland\">Swaziland</option>\r\n");
      out.write("            <option value=\"Syrie\">Syrie</option>\r\n");
      out.write("            <option value=\"Tadjikistan\">Tadjikistan</option>\r\n");
      out.write("            <option value=\"Taiwan\">Taiwan</option>\r\n");
      out.write("            <option value=\"Tonga\">Tonga</option>\r\n");
      out.write("            <option value=\"Tanzanie\">Tanzanie</option>\r\n");
      out.write("            <option value=\"Tchad\">Tchad</option>\r\n");
      out.write("            <option value=\"Thailande\">Thailande</option>\r\n");
      out.write("            <option value=\"Tibet\">Tibet</option>\r\n");
      out.write("            <option value=\"Timor_Oriental\">Timor_Oriental</option>\r\n");
      out.write("            <option value=\"Togo\">Togo</option>\r\n");
      out.write("            <option value=\"Trinite_et_Tobago\">Trinite_et_Tobago</option>\r\n");
      out.write("            <option value=\"Tristan da cunha\">Tristan de cuncha</option>\r\n");
      out.write("            <option value=\"Tunisie\">Tunisie</option>\r\n");
      out.write("            <option value=\"Turkmenistan\">Turmenistan</option>\r\n");
      out.write("            <option value=\"Turquie\">Turquie</option>\r\n");
      out.write("            <option value=\"Ukraine\">Ukraine</option>\r\n");
      out.write("            <option value=\"Uruguay\">Uruguay</option>\r\n");
      out.write("            <option value=\"Vanuatu\">Vanuatu</option>\r\n");
      out.write("            <option value=\"Vatican\">Vatican</option>\r\n");
      out.write("            <option value=\"Venezuela\">Venezuela</option>\r\n");
      out.write("            <option value=\"Vierges_Americaines\">Vierges_Americaines</option>\r\n");
      out.write("            <option value=\"Vierges_Britanniques\">Vierges_Britanniques</option>\r\n");
      out.write("            <option value=\"Vietnam\">Vietnam</option>\r\n");
      out.write("            <option value=\"Wake\">Wake</option>\r\n");
      out.write("            <option value=\"Wallis et Futuma\">Wallis et Futuma</option>\r\n");
      out.write("            <option value=\"Yemen\">Yemen</option>\r\n");
      out.write("            <option value=\"Yougoslavie\">Yougoslavie</option>\r\n");
      out.write("            <option value=\"Zambie\">Zambie</option>\r\n");
      out.write("            <option value=\"Zimbabwe\">Zimbabwe</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Téléphone</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"tel\" name=\"telephone\" id=\"telephone\" placeholder=\"Votre numero\" class=\"dim_block2\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Email :</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"email\" name=\"email\" placeholder=\"Adresse mail\" class=\"dim_block2\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Vos commentaires :</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"text\" name=\"commentaires\" class=\"dim_block3\">\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("    </fieldset>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Envoyer\" class=\"dim_block4\" id=\"colorBlock\">\r\n");
      out.write("    <input type=\"reset\" value=\"Annuler\" class=\"dim_block4\" id=\"colorBlock\">\r\n");
      out.write("</form>\r\n");
      out.write("<a href=\"accueil\">Accueil</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
